apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}-secret-store
  namespace: {{ .Values.namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.region }}
      # No auth block needed.
      # ESO uses EC2 instance IAM role automatically
      # via metadata service: 169.254.169.254
